#!/bin/bash
# Script build cho nhieu phien ban Revit (Linux/macOS)
# Chi huong dan - can chay tren Windows de build thuc te

echo "================================================"
echo "  Multi-Version Revit Build Instructions"
echo "================================================"
echo ""
echo "⚠️  Revit add-ins require Windows and MSBuild"
echo ""
echo "To build for all Revit versions (2020-2026):"
echo ""
echo "1. On Windows machine, open PowerShell"
echo "2. Navigate to: Quoc_Mep folder"
echo "3. Run:"
echo "   .\\build-all-versions.ps1"
echo ""
echo "Or build specific versions:"
echo "   .\\build-all-versions.ps1 -Versions 2023,2024"
echo ""
echo "Output will be in: bin\\Release\\Revit{Version}\\"
echo ""
echo "================================================"
echo ""
echo "Alternative: Build in VS Code on Windows"
echo "1. Open Quoc_MEP.csproj in Visual Studio"
echo "2. Select Configuration: Release"
echo "3. Build > Rebuild Solution"
echo "4. Change RevitVersion in csproj for each version"
echo ""
